DROP DATABASE IF EXISTS CZtours;

CREATE DATABASE CZtours CHARACTER SET utf8;

USE CZtours;

CREATE TABLE USER
(
	uId INT PRIMARY KEY AUTO_INCREMENT,
	uName VARCHAR(50) NOT NULL,
	uPwd VARCHAR(100) NOT NULL,
	mName VARCHAR(30) NULL,
	mSex INT NULL,
	mCity VARCHAR(20) NULL,
	mDate DATE NULL,
	mSign VARCHAR(300) NULL,
	mPhoto VARCHAR(300) NULL,
	iCity VARCHAR(30) NULL,
	iAddress VARCHAR(50) NULL,
	iPhone VARCHAR(11) NULL,
	iOffice INT NULL,
	iStaus INT NULL,
	iName VARCHAR(30) NULL
);

CREATE TABLE Scenic
(
	sId INT PRIMARY KEY AUTO_INCREMENT,
	sName VARCHAR(50) NOT NULL,
	sContent VARCHAR(500) NOT NULL,
	sPhoto VARCHAR(200) NOT NULL,
	sDescribe VARCHAR(30) NOT NULL,
	sCreatetime DATE NOT NULL
);

CREATE TABLE Comm
(
	cId INT PRIMARY KEY AUTO_INCREMENT,
	cName VARCHAR(40) NOT NULL,
	cPrice DOUBLE NOT NULL,
	cFreight VARCHAR(20) NOT NULL,
	cDetails VARCHAR(300) NOT NULL,
	cCreateTime DATE NOT NULL
);

CREATE TABLE ShopCar
(
	sId INT PRIMARY KEY AUTO_INCREMENT,
	sName VARCHAR(20) NOT NULL,
	sPrice DOUBLE NOT NULL,
	sPhoto VARCHAR(300) NOT NULL,
	sDate DATE NOT NULL,
	uId INT NOT NULL,
	cId INT NULL
);